### PR TITLE
Add aarch64 and ppc64le architectures

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
Rebuild and merge after libva was merged. @hmaarrfk

**Comment by hmaarrfk** [comment]
ps you can also add things to the "migrator" so that these PRs get made successively automaticaly.

**Comment by hmaarrfk** [comment]
it seems that there are some overlinking errors.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
